### ISSUE TITLE
Difference in number of conformers

### ISSUE THREAD

**Issue by ThiagoReschutzegger** [AIRI-Institute/nablaDFT#1]
The paper says there are 5340152 total conformations. However, if you count all the conformations in the [tar archive with xyz files](https://n-usr-31b1j.s3pd02.sbercloud.ru/b-usr-31b1j-qz9/data/nablaDFT/conformations_archive.tar), there are 5369546 total conformations. The difference can also be seen in the summary.csv file. As an example, the molecule with the `MOSES id` 1593105 has 5 conformers in the XYZ file but 3 in the summary.csv file.

Can you explain why that happens? Thanks!

**Comment by KuzmaKhrabrov** [comment]
Hello! Thank you for your question. This difference in conformations number happened because of computational problems (ether DFT cycle didn't converge, or files were corrupted in the transferring problems). I will take a look at these cases.
