### ISSUE TITLE
Missing reference in README.md

### ISSUE THREAD

**Issue by KonstantinUshenin** [AIRI-Institute/nablaDFT#10]
The link '[Fast and Uncertainty-Aware Directional Message Passing for Non-Equilibrium Molecules (DimeNet++)](https://github.com/ilya-shenbin/dimenet)' in README.md is broken. I wanted to find the original realization and fix this, but I could not find the proper repository.

**Comment by KuzmaKhrabrov** [comment]
Thank you! I have updated the link.
