### ISSUE TITLE
About data in the summary.csv

### ISSUE THREAD

**Issue by EBGU** [AIRI-Institute/nablaDFT#22]
Hi,

Your work is really awesome!
I am trying to train models with atomic DFT features like Löwdin atomic charges, but the wavefunc dataset is so large. Currently the summary.csv (https://n-usr-31b1j.s3pd12.sbercloud.ru/b-usr-31b1j-qz9/data/nablaDFT/summary.csv) is not available, so I cannot download and check. I wonder if I could find atomic charges in the summary.csv? Also, may I ask when the update would be ready for download?
Thank you so much!

**Comment by KuzmaKhrabrov** [comment]
Hello!

Here is an updated link to the summary file: https://a002dlils-kadurin-nabladft.obs.ru-moscow-1.hc.sbercloud.ru/data/nablaDFT/summary.csv

Unfortunately at this point Löwdin atomic charges are only available from the wave functions files.

**Comment by EBGU** [comment]
Thank you！
