### ISSUE TITLE
Installation is broken because of pytorch-scatter or pytorch-cluster

### ISSUE THREAD

**Issue by KonstantinUshenin** [AIRI-Institute/nablaDFT#24]
I was working with demos-d6203f8b and was trying to install nablaDFT on bare environment with Python 3.10

I called:

`pip install .`

I got

`ERROR: torch_scatter-2.1.2+pt22cu121-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.`

I called:

`python3 -m setup.py install`

Then I called 

`import nablaDFT`

this returned

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[8], line 1
----> 1 import nablaDFT

File ~/anaconda3/envs/nablaDFTdocs/lib/python3.10/site-packages/nablaDFT-2.0.0-py3.10.egg/nablaDFT/__init__.py:4
      2 from . import phisnet
      3 from . import graphormer
----> 4 from . import gemnet_oc
      5 from . import dimenetplusplus
      6 from . import equiformer_v2

File ~/anaconda3/envs/nablaDFTdocs/lib/python3.10/site-packages/nablaDFT-2.0.0-py3.10.egg/nablaDFT/gemnet_oc/__init__.py:1
----> 1 from .gemnet_oc import GemNetOCLightning, GemNetOC
      2 from .loss import L2Loss

File ~/anaconda3/envs/nablaDFTdocs/lib/python3.10/site-packages/nablaDFT-2.0.0-py3.10.egg/nablaDFT/gemnet_oc/gemnet_oc.py:10
      8 from torch.optim import Optimizer
      9 from torch.optim.lr_scheduler import LRScheduler
---> 10 from torch_scatter import segment_coo, scatter
     11 from torch_geometric.nn import radius_graph
     12 from torch_geometric.data import Data

ModuleNotFoundError: No module named 'torch_scatter'
```

Then I tries `%pip install https://data.pyg.org/whl/torch-2.2.0%2Bcu121/torch_scatter-2.1.2%2Bpt22cu121-cp39-cp39-linux_x86_64.whl`

this returned

`ERROR: torch_scatter-2.1.2+pt22cu121-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.`

**Comment by BerAnton** [comment]
Hello!

Thank you for posting this issue and sorry for the inconvenience.
Currently we're preparing big update for nablaDFT and some changes may not be presented in main branch.
Use setup.py from qhnet branch.
