### ISSUE TITLE
MANIFEST.in missing includes

### ISSUE THREAD

**Issue by tomfu1** [AIRI-Institute/nablaDFT#25]
The following script:

```
python -m venv env
env/bin/pip install --upgrade pip
env/bin/pip install torch wheel setuptools
env/bin/pip install torch-scatter torch-sparse
env/bin/pip install git+https://github.com/AIRI-Institute/nablaDFT.git
env/bin/python -c 'import nablaDFT'
```

generates the following error:

```FileNotFoundError: [Errno 2] No such file or directory: '/Users/.../lib/python3.11/site-packages/nablaDFT/equiformer_v2/Jd.pt```

Adding the following two lines to `MANIFEST.in` results in a successful import:

```
include nablaDFT/equiformer_v2/Jd.pt
include nablaDFT/escn/Jd.pt
```

Also, I understand that `torch` is used in setup.py and therefore cannot be included as a dependency, but why can't `torch-scatter` and `torch-parse`?

**Comment by KuzmaKhrabrov** [comment]
Hello!

Thank you for posting this issue and sorry for the inconvenience.
Currently we're preparing big update for nablaDFT and some changes may not be presented in main branch.
Use setup.py from qhnet branch.

**Comment by KuzmaKhrabrov** [comment]
Thank you again for your issue! Now the setup file in the man branch is updated.
