### ISSUE TITLE
How to reproduce the experiments that training PhiSNet model on nablaDFT

### ISSUE THREAD

**Issue by ismsgithub** [AIRI-Institute/nablaDFT#4]
Hi,
    nablaDFT is a very useful database for us. It contains such a large amount of data that is very important for machine learning. The main question is about training PhiSNet. I tried to use the "database_training_2k" at the beginning, but, there is no args text for the training. And when I use the args text for "database_10k" in the "config" folder, I can't get the number of training and valid dataset. I can't find any setting about valid dataset.

**Comment by KuzmaKhrabrov** [comment]
Hello,
Thank you and sorry for the inconvenience! I have added the corresponding config files. The train/validation split was just a random 90/10.
