### ISSUE TITLE
Energy and force units

### ISSUE THREAD

**Issue by hyuntae-cho** [AIRI-Institute/nablaDFT#42]
Hi, I have a question about units in datasets.
Your paper seems to report Hartree, Hartree/AA for energy and forces, however some of the codes uses eV instead of Hartree. 
Could you clarify units of energy and forces ?

**Comment by KuzmaKhrabrov** [comment]
Hello! Thank you for the interest and the question! 
All energy/forces databases use Hartree, Hartree/AA, while the hamiltonian databases use Hartree, Hartree/Bohr. Regarding the codes, used units are defined in the corresponding configs files.
