### ISSUE TITLE
Download links not accessible

### ISSUE THREAD

**Issue by mireklzicar** [AIRI-Institute/nablaDFT#7]
Hi, 
thanks for such a wonderful dataset. Unfortunately I cannot access nor download the files, I wanted for example the conformations: "https://n-usr-31b1j.s3pd02.sbercloud.ru/b-usr-31b1j-qz9/data/nablaDFT/conformations_archive.tar" but I cannot download anything from n-usr-31b1j.s3pd02.sbercloud.ru I am in Czech Republic (EU); are the accesses blocked or is it some temporary unavailibility?

**Comment by KuzmaKhrabrov** [comment]
Hello,
Thank you and sorry for the inconvenience! I have updated the links, please, try again with the new ones.

**Comment by mireklzicar** [comment]
Thanks, now it works! It has also a solid download speed.

**Comment by mireklzicar** [comment]
One more download links problem, this time with wavefunctions. I can for instance download "archive_small_3_f_9_9.tar", but I cannot download these "moses_wfns_big" such as https://n-usr-31b1j.s3pd12.sbercloud.ru/b-usr-31b1j-qz9/data/moses_wfns_big/wfns_moses_conformers_archive_32.tar downloading them throws "ERROR 403: Forbidden" / "Access denied".

**Comment by KuzmaKhrabrov** [comment]
> One more download links problem, this time with wavefunctions. I can for instance download "archive_small_3_f_9_9.tar", but I cannot download these "moses_wfns_big" such as https://n-usr-31b1j.s3pd12.sbercloud.ru/b-usr-31b1j-qz9/data/moses_wfns_big/wfns_moses_conformers_archive_32.tar downloading them throws "ERROR 403: Forbidden" / "Access denied".

Sorry for the inconvenience, we are preparing a big update and will post the new links shortly.

**Comment by mireklzicar** [comment]
Perfect, I am looking forward. Let me know in this issue when its done, then we can close it

**Comment by KuzmaKhrabrov** [comment]
Hello! By now you can use the updated links from 1.0 branch. Moreover, we plan to open twice more data in June
